##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [1]:
import numpy as np

# Sayılardan oluşan bir boyutlu array oluşturma
array = np.array([1, 2, 3, 4, 5], dtype=int)

# Array'in boyutunu ve eleman sayısını kontrol etme
boyut = array.ndim
eleman_sayısı = array.size

print("Array'in boyutu:", boyut)
print("Array'in eleman sayısı:", eleman_sayısı)


Array'in boyutu: 1
Array'in eleman sayısı: 5


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [4]:
# İki boyutlu array oluşturma
array_2d = np.array([[1, 2, 6, 7], [4, 3, 9, 5]])

# Üç boyutlu array oluşturma
array_3d = np.array([[[7, 5, 14], [21, 8, 11]], [[8, 6, 20], [14, 3, 9]]])

# İki boyutlu array'in boyutunu, eleman sayısını, satır ve sütun bilgilerini alma
boyut_2d = array_2d.ndim
eleman_sayısı_2d = array_2d.size
satır_2d, sutun_2d = array_2d.shape

# Üç boyutlu array'in boyutunu, eleman sayısını, satır ve sütun bilgilerini alma
boyut_3d = array_3d.ndim
eleman_sayısı_3d = array_3d.size
satır_3d, sütun_3d, derinlik_3d = array_3d.shape

print("İki boyutlu array:")
print(array_2d)
print("Boyutu:", boyut_2d)
print("Eleman sayısı:", eleman_sayısı_2d)
print("Satır sayısı:", satır_2d)
print("Sütun sayısı:", sutun_2d)

print("\nÜç boyutlu array:")
print(array_3d)
print("Boyutu:", boyut_3d)
print("Eleman sayısı:", eleman_sayısı_3d)
print("Satır sayısı:", satır_3d)
print("Sütun sayısı")


İki boyutlu array:
[[1 2 6 7]
 [4 3 9 5]]
Boyutu: 2
Eleman sayısı: 8
Satır sayısı: 2
Sütun sayısı: 4

Üç boyutlu array:
[[[ 7  5 14]
  [21  8 11]]

 [[ 8  6 20]
  [14  3  9]]]
Boyutu: 3
Eleman sayısı: 12
Satır sayısı: 2
Sütun sayısı


##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [1]:
#İki boyutlu arraydaki 2 elemanına ulaşalım

In [5]:
ikinci_eleman = array_2d[0, 1]  # Satır indeksi 0, sütun indeksi 1

print("İki boyutlu arrayin 2. elemanı:", ikinci_eleman)


İki boyutlu arrayin 2. elemanı: 2


In [2]:
#İki boyutlu arraydaki 7 elemanına ulaşalım

In [7]:
yedinci_eleman = array_2d[0, 3]  # İlk satır, dördüncü sütun

print("İki boyutlu arrayin 7. elemanı:", yedinci_eleman)

İki boyutlu arrayin 7. elemanı: 7


In [3]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım

In [8]:
dokuzuncu_eleman = array_3d[1, 1, 2]  # İkinci küpün, ikinci satırı, üçüncü sütunu

print("Üç boyutlu arrayin 9. elemanı:", dokuzuncu_eleman)

Üç boyutlu arrayin 9. elemanı: 9


In [4]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım

In [10]:
besinci_eleman = array_3d[0, 0, 1]  # İlk küpün, ilk satırı, ikinci sütunu

print("Üç boyutlu arrayin 5. elemanı:", besinci_eleman)

Üç boyutlu arrayin 5. elemanı: 5


##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [5]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım


In [11]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım

ikinci_eleman = array_2d[0, 1]  # 0. satır, 1. sütun
altıncı_eleman = array_2d[0, 2]  # 0. satır, 2. sütun

print("İki boyutlu arrayin 2. elemanı:", ikinci_eleman)
print("İki boyutlu arrayin 6. elemanı:", altıncı_eleman)

İki boyutlu arrayin 2. elemanı: 2
İki boyutlu arrayin 6. elemanı: 6


In [12]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım

yirmibirinci_eleman = array_3d[0, 1, 0]  
sekizinci_eleman = array_3d[0, 1, 1]  
onbirinci_eleman = array_3d[0, 1, 2]  

print("Üç boyutlu arrayin 21. elemanı:", yirmibirinci_eleman)
print("Üç boyutlu arrayin 8. elemanı:", sekizinci_eleman)
print("Üç boyutlu arrayin 11. elemanı:", onbirinci_eleman)

Üç boyutlu arrayin 21. elemanı: 21
Üç boyutlu arrayin 8. elemanı: 8
Üç boyutlu arrayin 11. elemanı: 11


In [13]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım

altıncı_eleman = array_3d[1, 0, 1]  
yirmi_eleman = array_3d[1, 1, 2]  

print("Üç boyutlu dizinin 6. elemanı:", altıncı_eleman)
print("Üç boyutlu dizinin 20. elemanı:", yirmi_eleman)

Üç boyutlu dizinin 6. elemanı: 6
Üç boyutlu dizinin 20. elemanı: 9


##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [14]:
# İki tane 5x3 boyutunda sıfırlardan oluşan array oluşturma
sifirlar_array = np.zeros((5, 3))

# İki tane 5x3 boyutunda birlerden oluşan array oluşturma
birler_array = np.ones((5, 3))

# Satır bazında birleştirme
birleştirilmis_satir = np.concatenate((sifirlar_array, birler_array), axis=0)

# Sütun bazında birleştirme
birleştirilmis_sutun = np.concatenate((sifirlar_array, birler_array), axis=1)

print("Satır bazında birleştirme:")
print(birleştirilmis_satir)

print("\nSütun bazında birleştirme:")
print(birleştirilmis_sutun)


Satır bazında birleştirme:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Sütun bazında birleştirme:
[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
